#!/usr/bin/env python3
import os, sys
from g4f.client import Client
from rich import print
from rich.console import Console
from rich.prompt import Confirm
console = Console()
prompt = sys.argv
prompt.pop(0)
prompt = " ".join(prompt)

client = Client()
try:
    tasks = [f"task {n}" for n in range(1, 11)]

    with console.status("[bold green]:brain: Generating...") as status:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": """You help to use the Linux terminal, when you get request, you should response in a single line of commands, without commentaries,without descriptions, that will be executed in the terminal."""},
                { "role": "user", "content": "create a test.py file" },
                { "role": "assistant", "content": "touch test.py" },
                { "role": "user", "content": "move the test.txt to my home directory" },
                { "role": "assistant", "content": "mv mama.txt ~/" },
                { "role": "user", "content": "write a small test.py script and run it" },
                { "role": "assistant", "content": "touch test.py & cat \"print(\"test!\")\" >> test.py & python3 test.py" },
                { "role": "user", "content": prompt }
            ],
            model="gpt-3.5-turbo",
        )
        result = chat_completion.choices[0].message.content
        result = result.replace("```bash","").replace("```","")
    print("[bold green]"+result+"[/bold green]")
    execute = Confirm.ask("Execute?")
    if( execute ):
        os.system(result)
except Exception as e:
    print(chat_completion)